###############################################################################
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corporation 2021. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
###############################################################################

displayName: IBM Wazi Ansible Plugin
description: Adds Ansible with z/OS collections to IBM Wazi Developer workspaces
tags: ["Ansible", "z/OS", "IBM Z"]
icon: /images/type-wazi.svg
